apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: openeuler
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: yangwei
  kubernetes.ops.region: hk
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/defect-manager-prod
  newTag: ab6ccae857c876576b9117c9055904863f4fef75
kind: Kustomization
namespace: cve-defect-manager
resources:
- manager-deployment.yaml
- ingress.yaml
- service.yaml
