apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetingserver-deployment
  namespace: openeuler-meetingserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meetingserver
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'openeuler-meeting'
        vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0600"
        vault.hashicorp.com/agent-inject-perms-ca.pem: "0600"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/mindspore/openeuler-meeting'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
          {{- with secret "internal/data/mindspore/openeuler-meeting" -}}  
          {{ .Data.data.config }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-ca.pem: 'internal/data/mindspore/openeuler-meeting'
        vault.hashicorp.com/agent-inject-template-ca.pem: |  
          {{- with secret "internal/data/mindspore/openeuler-meeting" -}}  
          {{ .Data.data.MysqlCA }}
          {{- end }}
      labels:
        app: meetingserver
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: CONFIG_PATH
          value: /vault/secrets/secrets.yaml
        - name: MYSQL_TLS_PEM_PATH
          value: /vault/secrets/ca.pem
        image: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/openeuler/meetingserver:master-6148c8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        name: meetingserver
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
          requests:
            cpu: "1"
            memory: 1000Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      serviceAccountName: openeuler-meeting
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30