apiVersion: apps/v1
kind: Deployment
metadata:
  name: signatrust-control-server
  namespace: openeuler-signatrust
spec:
  replicas: 1
  selector:
    matchLabels:
      component: signatrust-control-server
  template:
    metadata:
      labels:
        component: signatrust-control-server
    spec:
      containers:
      - command:
        - /app/control-server
        env:
        - name: RUST_LOG
          value: info
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/signatrust/signatrust-control-server:518a21b4de368ef502eaa7339c70a13dbead1edc
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        name: signatrust-server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 8000m
            memory: 8000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        volumeMounts:
        - mountPath: /app/config/server.toml
          name: secret
          subPath: control-server-toml-new
        - mountPath: /signatrust/.data/certs/server/ca_root.pem
          name: secret
          subPath: ca-root-pem
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      initContainers:
      - command:
        - /bin/sh
        - -c
        - '# TODO: Use commit it instead of latest master

          git clone https://gitee.com/openeuler/signatrust

          cd signatrust

          git checkout $CONTROL_SERVER_TAG

          sqlx database create

          sqlx migrate run

          '
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: signatrust-secrets
        - name: CONTROL_SERVER_TAG
          value: b319304bf669e4cb6c9c764842e23f34193d7e93
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/signatrust/rust-sqlx:latest
        name: prepare-table
      nodeSelector:
        os.architecture: amd64
        usage: test
      volumes:
      - name: secret
        secret:
          secretName: signatrust-secrets
