apiVersion: v1
kind: ConfigMap
metadata:
  name: copr-frontend
  namespace: fedora-copr-prod
data:
  httpd.conf: |
    Listen 5000

    <VirtualHost 0.0.0.0>
        ErrorLog /dev/stdout
        CustomLog /dev/stdout combined
        WSGIPassAuthorization On
        WSGIDaemonProcess 127.0.0.1 user=copr-fe group=copr-fe threads=5
        WSGIScriptAlias / /usr/share/copr/coprs_frontend/application
        WSGIProcessGroup 127.0.0.1
        <Directory /usr/share/copr>
            WSGIApplicationGroup %{GLOBAL}
            Require all granted
        </Directory>
    </VirtualHost>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copr-keygen
  namespace: fedora-copr-prod
data:
  copr-keygen.conf: |
    Listen 0.0.0.0:5003

    <VirtualHost 0.0.0.0:5003>
        ServerName 127.0.0.1

        WSGIPassAuthorization On
        WSGIDaemonProcess 127.0.0.1 user=copr-signer group=copr-signer threads=5
        WSGIScriptAlias / /usr/share/copr-keygen/application.py
        WSGIProcessGroup 127.0.0.1

        ErrorLog "/dev/stdout"
        CustomLog "/dev/stdout" common

        TimeOut 300

        <Directory /usr/share/copr-keygen>
            WSGIApplicationGroup %{GLOBAL}
            # apache 2.2 (el6, F17)
            #Order deny,allow
            #Allow from all
            # apache 2.4 (F18+)
            Require all granted
        </Directory>
    </VirtualHost>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copr-resalloc
  namespace: fedora-copr-prod
data:
  pools.yaml: |
    local_x86_64_normal_prod:
        max: 20
        max_starting: 10
        max_prealloc: 1
        tags:
        - copr_builder
        - arch_noarch
        - arch_x86_64
        - arch_x86_64_native
        - arch_i386
        - arch_i386_native
        - arch_i586
        - arch_i586_native
        - arch_i686
        - arch_i686_native
        cmd_new: "/home/resalloc/provision/local-new-x86"
        cmd_delete: "/home/resalloc/provision/local-delete"
        cmd_livecheck: "/home/resalloc/provision/check-pod"
        livecheck_period: 180
        reuse_opportunity_time: 0
        reuse_max_count: 0
        reuse_max_time: 3600

    local_aarch64_normal_prod:
        max: 20
        max_starting: 10
        max_prealloc: 1
        tags:
        - copr_builder
        - arch_aarch64
        - arch_aarch64_native
        cmd_new: "/home/resalloc/provision/local-new-aarch64"
        cmd_delete: "/home/resalloc/provision/local-delete"
        cmd_livecheck: "/home/resalloc/provision/check-pod"
        livecheck_period: 180
        reuse_opportunity_time: 0
        reuse_max_count: 0
        reuse_max_time: 3600

  ecs_servers.yaml: |
      # 地区
      region: cn-east-3

      # 服务器名称前缀
      name_prefix: eur-prod-worker

      # 项目的唯一标识,和地区相关
      projectId: 0612bdc78f80251f2fcac017ebad7ad7

      # 待创建云服务器所属虚拟私有云的ID
      vpcId: 0144e89a-dde3-4a09-9680-4293cc914785

      # 待创建云服务器所在的子网信息,需要指定vpcid对应VPC下的子网ID
      subnetId: 2a941aec-dd59-4565-93f5-75ae1140c4aa

      # 安全组ID
      security_group_id: e6bb91ad-0c9a-4795-8ee1-3d9b9f6b6c8e

      # 云服务器系统盘对应的磁盘类型, [SATA(普通IO磁盘类型), SAS(高IO磁盘类型), SSD(超高IO磁盘类型)]
      volumetype: SSD

      # 创建云服务器后使用id查询ip每次等待时间(单位：秒)
      waiting_time: 10

      # 创建云服务器后使用id查询ip的次数
      query_times: 18

      # 服务器启动时间(单位：秒)
      server_boot_time: 60

      # 云服务器允许的最大容量，当申请创建的数量超过剩余容量则不再创建
      max_servers_number: 500

      # 列表查询的最大数
      max_list_number: 1000

      # sshkey name
      key_name: eur

      user_data: IyEvYmluL2Jhc2gKCnNlZCAtaSAncy8uKmNvcHItZnJvbnRlbmQvMTcyLjE2LjIuMTQ1IGNvcHItZnJvbnRlbmQvZycgL2V0Yy9ob3N0cwpzZWQgLWkgJ3MvLipjb3ByLWRpc3RnaXQvMTcyLjE2LjIuMjQyICBjb3ByLWRpc3RnaXQvZycgL2V0Yy9ob3N0cwo=

      # 规格映射
      flavorMapping:
        x86:
            imageRef: 83801db6-bab1-47c6-ae5f-445ac9fd8ce6
            l1: c3.xlarge.2
            l2: c3ne.xlarge.2
            l3: hc2.xlarge.2
        aarch64:
            imageRef: 4ca2bf4c-f912-4cec-9879-f5e5d9ed32d1
            l1: kc1.xlarge.2
            l2: kc1.xlarge.2
            l3: kc1.xlarge.2

      # 架构映射
      archMapping:
        x86:
          - c6s.large.2
          - c6s.xlarge.2
          - c6s.2xlarge.2
          - c6s.3xlarge.2
          - c6s.4xlarge.2
          - c6s.6xlarge.2
          - c6s.8xlarge.2
          - c6s.12xlarge.2
          - c6s.16xlarge.2
          - c6.large.2
          - c6.large.4
          - c6.xlarge.2
          - c6.xlarge.4
          - c6.2xlarge.2
          - c6.2xlarge.4
          - c6.3xlarge.2
          - c6.3xlarge.4
          - c6.4xlarge.2
          - c6.4xlarge.4
          - c6.6xlarge.2
          - c6.6xlarge.4
          - c6.8xlarge.2
          - c6.8xlarge.4
          - c6.12xlarge.2
          - c6.12xlarge.4
          - c6.16xlarge.2
          - c6.16xlarge.4
          - c6.22xlarge.2
          - c6.22xlarge.2.physica
          - c6.22xlarge.4
          - c6.22xlarge.4.physical
          - c7.large.2
          - c7.large.4
          - c7.xlarge.2
          - c7.xlarge.4
          - c7.2xlarge.2
          - c7.2xlarge.4
          - c7.3xlarge.2
          - c7.3xlarge.4
          - c7.4xlarge.2
          - c7.4xlarge.4
          - c7.6xlarge.2
          - c7.6xlarge.4
          - c7.8xlarge.2
          - c7.8xlarge.4
          - c7.12xlarge.2
          - c7.12xlarge.4
          - c7.16xlarge.2
          - c7.16xlarge.4
          - c7.24xlarge.2
          - c7.24xlarge.4
          - c7.32xlarge.2
          - c7.32xlarge.4
          - c3ne.large.2
          - c3ne.large.4
          - c3ne.xlarge.2
          - c3ne.xlarge.4
          - c3ne.2xlarge.2
          - c3ne.2xlarge.4
          - c3ne.4xlarge.2
          - c3ne.4xlarge.4
          - c3ne.8xlarge.2
          - c3ne.8xlarge.4
          - c3ne.15xlarge.2
          - c3ne.15xlarge.4
          - s6.small.1
          - s6.medium.2
          - s6.medium.4
          - s6.large.2
          - s6.large.4
          - s6.xlarge.2
          - s6.xlarge.4
          - s6.2xlarge.2
          - s6.2xlarge.4
          - sn3.small.1
          - sn3.medium.2
          - sn3.medium.4
          - sn3.large.2
          - sn3.large.4
          - sn3.xlarge.2
          - sn3.xlarge.4
          - sn3.2xlarge.2
          - sn3.2xlarge.4
          - sn3.4xlarge.2
          - sn3.4xlarge.4
          - m6.large.8
          - m6.xlarge.8
          - m6.2xlarge.8
          - m6.3xlarge.8
          - m6.4xlarge.8
          - m6.6xlarge.8
          - m6.8xlarge.8
          - m6.16xlarge.8
          - m6.22xlarge.8.physical
          - m3ne.large.8
          - m3ne.xlarge.8
          - m3ne.2xlarge.8
          - m3ne.3xlarge.8
          - m3ne.4xlarge.8
          - m3ne.6xlarge.8
          - m3ne.8xlarge.8
          - m3ne.15xlarge.8
          - e3.7xlarge.12
          - e3.14xlarge.12
          - e3.26xlarge.14
          - e3.52xlarge.14
          - d6.xlarge.4
          - d6.2xlarge.4
          - d6.4xlarge.4
          - d6.6xlarge.4
          - d6.8xlarge.4
          - d6.12xlarge.4
          - d6.16xlarge.4
          - d6.18xlarge.4
          - d3.xlarge.8
          - d3.2xlarge.8
          - d3.4xlarge.8
          - d3.6xlarge.8
          - d3.8xlarge.8
          - d3.12xlarge.8
          - d3.14xlarge.10
          - ir3.large.4
          - ir3.xlarge.4
          - ir3.2xlarge.4
          - ir3.4xlarge.4
          - ir3.8xlarge.4
          - i3.2xlarge.8
          - i3.4xlarge.8
          - i3.8xlarge.8
          - i3.12xlarge.8
          - i3.15xlarge.8
          - i3.16xlarge.8
          - p2vs.2xlarge.8
          - p2vs.4xlarge.8
          - p2vs.8xlarge.8
          - p2vs.16xlarge.8
          - p2v.2xlarge.8
          - p2v.4xlarge.8
          - p2v.8xlarge.8
          - p2v.16xlarge.8
          - g6v.2xlarge.2
          - g6v.2xlarge.4
          - g6v.4xlarge.4
          - g6.xlarge.4
          - g6.4xlarge.4
          - g6.6xlarge.4
          - g6.9xlarge.7
          - g6.18xlarge.7
          - g5.8xlarge.4
          - pi2.2xlarge.4
          - pi2.4xlarge.4
          - pi2.8xlarge.4
          - pi1.2xlarge.4
          - pi1.4xlarge.4
          - pi1.8xlarge.4
          - ai1s.large.4
          - ai1s.xlarge.4
          - ai1s.2xlarge.4
          - ai1s.4xlarge.4
          - ai1s.8xlarge.4
          - ai1.large.4
          - ai1.xlarge.4
          - ai1.2xlarge.4
          - ai1.4xlarge.4
          - ai1.8xlarge.4
          - t6.small.1
          - t6.medium.2
          - t6.large.1
          - t6.large.2
          - t6.large.4
          - t6.xlarge.1
          - t6.xlarge.2
          - t6.xlarge.4
          - t6.2xlarge.1
          - t6.2xlarge.2
          - t6.2xlarge.4
          - t6.4xlarge.1
          - t6.4xlarge.2
        aarch64:
          - kai1s.xlarge.1
          - kai1s.2xlarge.1
          - kai1s.3xlarge.2
          - kai1s.4xlarge.1
          - kai1s.4xlarge.2
          - kai1s.6xlarge.2
          - kai1s.9xlarge.2
          - kai1s.12xlarge.2
          - kc1.small.1
          - kc1.large.2
          - kc1.large.4
          - kc1.xlarge.2
          - kc1.xlarge.4
          - kc1.2xlarge.2
          - kc1.2xlarge.4
          - kc1.3xlarge.2
          - kc1.3xlarge.4
          - kc1.4xlarge.2
          - kc1.4xlarge.4
          - kc1.6xlarge.2
          - kc1.6xlarge.4
          - kc1.8xlarge.2
          - kc1.8xlarge.4
          - kc1.12xlarge.2
          - kc1.12xlarge.4
          - kc1.15xlarge.2
          - km1.large.8
          - km1.xlarge.8
          - km1.2xlarge.8
          - km1.3xlarge.8
          - km1.4xlarge.8
          - km1.6xlarge.8
          - km1.8xlarge.8
          - km1.12xlarge.8
          - km1.15xlarge.8
          - ki1.2xlarge.4
          - ki1.4xlarge.4
          - ki1.6xlarge.4
          - ki1.8xlarge.4
          - ki1.12xlarge.4
          - ki1.16xlarge.4
          - physical.ks1.2xlarge

  builder_config: |
    Host *
        # For dynamically started VMs.
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null

        # For non-default paths to identity file.
        IdentityFile ~/.ssh/id_rsa

        # Ensure remote command uses proper line buffering for live logs
        # (so called live logs).
        RequestTTY=force

        # Keep control sockets open, to speedup subsequent command runs.
        ControlPath=/home/copr/ssh_socket_%h_%p_%r
        ControlMaster=auto
        ControlPersist=900

        Port=22

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copr-backend
  namespace: fedora-copr-prod
data:
  builder_config: |
    Host *
        # For dynamically started VMs.
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null

        # For non-default paths to identity file.
        IdentityFile ~/.ssh/id_rsa

        # Ensure remote command uses proper line buffering for live logs
        # (so called live logs).
        RequestTTY=force

        # Keep control sockets open, to speedup subsequent command runs.
        ControlPath=/home/copr/ssh_socket_%h_%p_%r
        ControlMaster=auto
        ControlPersist=900

        Port=22
