apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-deployment
  namespace: openeuler-software-pkg
spec:
  selector:
    matchLabels:
      app: watch
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: watch
    spec:      
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/software-package-watch:dev_watch-3e2d30
        imagePullPolicy: IfNotPresent        
        args:
        - --config-file=/opt/app/config/config.yaml
        name: watch        
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: db_host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: db_user
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: db_pwd
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: db_name
        - name: KAFKA_ADDRESS
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: kafka_address
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: access_token
        - name: KAFKA_VERSION
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: kafka_version
        - name: MONGODB_CONN
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: mongodb_conn
        - name: MONGODB_DB_NAME
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: mongodb_db_name
        - name: OM_APP_ID
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: om_app_id
        - name: OM_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: om_app_secret
        - name: ROBOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: robot_token
        - name: ROBOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: robot_username
        - name: ROBOT_EMAIL
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: robot_email
        - name: EMAIL_AUTH_CODE
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: email_auth_code
        - name: EMAIL_FROM
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: email_from
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: email_host
        - name: EMAIL_PORT
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: email_port
        volumeMounts:
        - mountPath: /opt/app/config/config.yaml
          name: watch-configmap
          subPath: config.yaml
      volumes:
      - configMap:
          defaultMode: 420
          name: watch-configmap
        name: watch-configmap

