resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- tls.yaml
namespace: nestos
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/nestos-website
  newTag: 1d779db6e2d8f013d51e64d20a94bcf42093de6b
